# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rmTNQDjSIT4CAv0JGmfZuL-hTKYJfiye
"""

# factorial
def factorial (num):
  return 1 if num == 1 else (num * factorial(num-1))
num=5
print (factorial(num))

# fibonacci
def fibonacci(num):
   return num if num<=1 else fibonacci(num-1)+ fibonacci (num-2)
nterms = 10
print ("fibonacci sequence")
for num in range(nterms):
  print(fibonacci(num))



