# -*- coding: utf-8 -*-
"""numpy_part2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GhhcuA3-x9qN69f5c0ihrPz8fnPK309P
"""

# statistics
import numpy as np
x=np.array([1,2,3,2])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

np.median(x)

np.median(y, axis=-1)

x.std()

a=np.tile(np.arange(0,40,10),(3,1))
print(a)
print("*************")
a=a.T
print(a)

b=np.array([0,1,2])
b

a+b

a=np.arange(0,40,10)
a.shape

a=a[:,np.newaxis] # adds a new axis --> 2D array
a.shape

a

a+b

a=np.array([[1,2,3],[4,5,6]])
a.ravel()  # returns a contagious flattened array

a.T

a.T.ravel()

# reshaping
print(a.shape)
print(a)

b=a.ravel()
print(b)

b=b.reshape([2,3])
b

# shape may also return a copy
a=np.zeros([3,2])
b=a.T.reshape(3*2)
b[0] =50
a

# 2D array will become 3D array
# 3D array will become 4D array
import numpy as np
z=np.array([1,2,3])
z

z[:, np.newaxis]



a=np.arange(4*3*2).reshape(4,3,2)
a.shape

a

a[0,2,1]



# resizing
a= np.arange(4)
a.resize((8,))
a

# sorting along an axis
a=np.array([[5,4,6],[2,3,2]])
b= np.sort(a,axis=1)
b

# in-plane sort
a.sort(axis=1)
a

#sorting with fancy indexing
a=np.array([4,3,1,2])
j=np.argsort(a)
j

a[j]