# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E75YQ47XrYCpeATMMpMNRVRsKvT7DmBO
"""

import pandas as pd
weather_data = [('1/1/2024', 32, 6, 'Rain'),
                ('1/2/2024', 35, 7, 'Sunny'),
                ('1/3/2024', 28, 2, 'Snow'),
                ('1/4/2024', 24, 7, 'Snow'),
                ('1/5/2024', 32, 4, 'Rain'),
              ]
df = pd.DataFrame(weather_data, columns = ['day','temperature','Windspeed','event'])
df

# get dimension of the table
df.shape  # total number of rows and columns

df.head() # to display initial 5 rows

df.tail() # displays last few rows

# slicing
df [1:4]

df.columns  # print columns in a table

df.day     # print particular column data

# another way of accessing column
df["day"]

# get data from 2 columns
df[['day','event']]

# get all temperatures
df["temperature"]

# print maximum temperature
df['temperature'].max()

df['temperature'].min()

df["temperature"].describe()

# select rows which has maximum temperature
df[df.temperature == df.temperature.max()]

# select only day column which has maximum temperature
df.day[df.temperature == df.temperature.max()]

