# -*- coding: utf-8 -*-
"""rev2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fSN-JLKWqkhiTxNjxoMm0FmDYL5RHZwe
"""

numbers = [1,2,3,4]
for num in numbers:
  if num ==4:
    break
  print(num)
else:
  print("in the else block")
print("Outside of for loop")

# to check whether a number is prime or not
num = int(input(" Enter a number:"))

isDivisible = False

i=2
while i<num:
  if num%i==0:
    isDivisible = True
    print("{} is divisible by {}".format(num,i))
    break
  i +=1
if isDivisible:
  print("{} is not a prime number". format(num))
else:
  print("{} is a prime number". format(num))

# print odd numbers present in a list
numbers= [1,2,3,4,5,6,7]
for num in numbers:
  if num%2==0:
    continue
  print(num)
else:
  print("else block")

# tuple
t = ()

t=(1,2,3)
print(t)

# tuple with mixed datatype
t=(1,'raju',28,'abc')
print(t)

# nested tuple
t=(1,(2,3,4),[1,'raju',28,'abc'])
print(t)

# only parenthesis is not enough
t = ('satish')
type(t)

# need a comma at the end
t = ('satish',)
type(t)

# parenthesis is optional
t = 'satish',
print(type(t))

# accessing elements in a tuple
t = ('satish','murali','naveen','brahma')
print(t[1])

# negative index
print(t[-1])

