# -*- coding: utf-8 -*-
"""Revision_matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yeGHPENrksqXH28OmminNbONyndigYDw
"""

import matplotlib.pyplot as plt
plt.plot([2,4,6,8,10])
plt.ylabel("Numbers")
plt.xlabel("Indices")
plt.title("MyPlot")
plt.show( )

plt.plot([1,2,3,4],[1,4,9,16])
plt.ylabel("Squares")
plt.xlabel("Numbers")
plt.grid()
plt.show()

plt.plot([1,2,3,4],[1,4,9,16], 'b^')
plt.grid()
plt.show()

import numpy as np
t = np.arange(0,5,0.2)

# blue dashes, red squares and green triangles
plt.plot(t, t**2, 'b--', label='^2')
plt.plot(t,t**2.2, 'rs', label='^2.2')
plt.plot(t,t**2.5, 'g^', label='^2.5')
plt.grid()
plt.legend()  # add legend based on line labels
plt.show()

x=[1,2,3,4]
y=[1,4,9,16]
plt.plot(x,y,linewidth=20)
plt.show()

# using set up
x1=[1,2,3,4]
x2=[1,4,9,16]
y1=[1,2,3,4]
y2=[2,4,6,8]
lines = plt.plot(x1,x2,y1,y1)

# use keyword args
plt.setp(lines[0], color='blue', linewidth = 10)


# or MATLAB style string value pairs
plt.setp(lines[1], 'color','grey','linewidth',10)
plt.grid()

# working with multiple figures and axes
def f(t):
  return np.exp(-t)* np.cos(2*np.pi*t)

t1 = np.arange(0,10,0.05)
t2 = np.arange(0,20,0.05)

plt.figure(1)

plt.subplot(212)
plt.grid()
plt.plot(t1,f(t1),'b-')

plt.subplot(211)
plt.plot(t2,np.cos(2*np.pi*t2), 'r--')
plt.show()